apiVersion: apps/v1
kind: Deployment
metadata:
  name: showtime-backend
  labels:
    app: showtime-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: showtime-backend
  template:
    metadata:
      labels:
        app: showtime-backend
    spec:
      containers:
        - name: showtime-backend
          image: likhithrajup/showtime-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://host.docker.internal:5432/showtime"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
            - name: SPRING_DATA_REDIS_HOST
              value: "host.docker.internal"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA
              value: "showtime"

          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "600m"
              memory: "1Gi"