apiVersion: v1
kind: Service
metadata:
  name: showtime-service
spec:
  type: NodePort
  selector:
    app: showtime-backend
  ports:
    - port: 8080        # Inside cluster
      targetPort: 8080 # Inside Pod
      nodePort: 30007  # Accessible externally